---
# https://hub.docker.com/r/linuxserver/homeassistant/tags
homeassistant_base_image: "lscr.io/linuxserver/homeassistant"
homeassistant_base_image_tag: "2024.8.1"

homeassistant_avahi_image_name: "homeassistant-avahi"
homeassistant_avahi_image_tag: "{{ homeassistant_base_image_tag }}-avahi"

homeassistant_env_default: {}

homeassistant_homekit_config_default:
  name: "HomeKit Bridge"
  advertise_ip: "{{ ansible_host }}"
  port: "21063"
  filter:
    include_entity_globs:
      - "*"

homeassistant_config_default:
  network: {}

  homekit:
    - "{{ homeassistant_homekit_config_default | combine(homeassistant_homekit_config, recursive=true) }}"
