---
# https://hub.docker.com/r/linuxserver/homeassistant/tags
homeassistant_base_image: "lscr.io/linuxserver/homeassistant"
homeassistant_base_image_tag: "2024.5.3"

homeassistant_avahi_image_name: "homeassistant-avahi"
homeassistant_avahi_image_tag: "{{ homeassistant_base_image_tag }}-avahi"

homeassistant_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"

homeassistant_env_default:
  TZ: "{{ homeassistant_docker_settings.tz }}"
  PUID: "{{ homeassistant_docker_settings.puid }}"
  PGID: "{{ homeassistant_docker_settings.pgid }}"

homeassistant_homekit_config_default:
  name: "HomeKit Bridge"
  advertise_ip: "{{ ansible_host }}"
  port: "21063"

homeassistant_config_default:
  homeassistant:
    time_zone: "{{ homeassistant_docker_settings.tz }}"

  network: {}

  homekit:
    - "{{ homeassistant_homekit_config_default | combine(homeassistant_homekit_config, recursive=true) }}"
