---
# https://hub.docker.com/r/linuxserver/homeassistant/tags
homeassistant_base_image: "lscr.io/linuxserver/homeassistant"
homeassistant_base_image_tag: "2024.5.3"

homeassistant_avahi_image_name: "homeassistant-avahi"
homeassistant_avahi_image_tag: "{{ homeassistant_base_image_tag }}-avahi"