---
namespace: artyorsh

name: smarthome

version: 1.0.1-dev

readme: README.md

authors:
  - artyorsh

description: Simplify the deployment and configuration of HomeAssistant, Zigbee2MQTT and Mosquitto, making them ready to connect to Apple Home.

license:
  - MIT

tags:
  - smarthome
  - iot
  - homeassistant
  - zigbee2mqtt
  - mosquitto

dependencies:
  "community.docker": ">=3.0.0"

repository: https://github.com/artyorsh/ansible-collection-smarthome
documentation: https://github.com/artyorsh/ansible-collection-smarthome
homepage: https://artyorsh.me
issues: https://github.com/artyorsh/ansible-collection-smarthome/issues

build_ignore: []
