---
homeassistant_port: 8123
homeassistant_install_dir: "/opt/docker/homeassistant"

homeassistant_env: {}

# https://home-assistant.io/docs/configuration/
# https://github.com/arsaboo/homeassistant-config/blob/master/configuration.yaml
homeassistant_config: {}

# https://community.home-assistant.io/t/using-homekit-component-inside-docker/45409/45?page=2
homeassistant_mdns_host_network_interface: "eth0"
homeassistant_mdns_docker_network_interface: ""

homeassistant_docker_settings: {}
