---
- name: "Install HomeAssistant"
  ansible.builtin.include_role:
    name: "homeassistant"
  vars:
    homeassistant_docker_settings: "{{ hostvars[inventory_hostname]['homeassistant_docker_settings'] | default(smarthome_docker_settings | combine({'network': smarthome_network})) }}"

- name: "Install Mosquitto"
  ansible.builtin.include_role:
    name: "mosquitto"
  vars:
    mosquitto_user: "{{ smarthome_user }}"
    mosquitto_docker_settings: "{{ hostvars[inventory_hostname]['mosquitto_docker_settings'] | default(smarthome_docker_settings) }}"

- name: "Install Zigbee2MQTT"
  when: smarthome_zigbee_adapter | length > 0
  ansible.builtin.include_role:
    name: "zigbee2mqtt"
  vars:
    zigbee2mqtt_docker_settings: "{{ hostvars[inventory_hostname]['zigbee2mqtt_docker_settings'] | default(smarthome_docker_settings | combine({'network': smarthome_network})) }}"
    zigbee2mqtt_config:
      mqtt:
        server: "mqtt://{{ mosquitto_service_id }}"
        user: "{{ smarthome_user.name }}"
        password: "{{ smarthome_user.password }}"

    zigbee2mqtt_adapter: "{{ smarthome_zigbee_adapter }}"
