---
# https://hub.docker.com/_/eclipse-mosquitto/tags
mosquitto_version: "latest"
mosquitto_install_dir: "/opt/docker/mosquitto"

mosquitto_env: {}

mosquitto_docker_settings: {}

# https://mosquitto.org/documentation/authentication-methods
mosquitto_user:
  name: "{{ ansible_user }}"
  password: "mosquitto"
