# https://www.zigbee2mqtt.io/guide/installation/02_docker.html
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-devices
---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    zigbee2mqtt_service_id: "zigbee2mqtt"
    zigbee2mqtt_env: "{{ zigbee2mqtt_env_default | combine(zigbee2mqtt_env) }}"
    zigbee2mqtt_config: "{{ zigbee2mqtt_config_default | combine(zigbee2mqtt_config, recursive=true) }}"

- name: "Create service directories"
  ansible.builtin.file:
    path: "{{ zigbee2mqtt_install_dir }}"
    state: "directory"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0770"

- name: "Template configuration.yml"
  ansible.builtin.template:
    src: "zigbee2mqtt-configuration.yaml.j2"
    dest: "{{ zigbee2mqtt_install_dir }}/configuration.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: "Ensure {{ zigbee2mqtt_network }} network exists"
  when: zigbee2mqtt_network != "host"
  community.docker.docker_network:
    name: "{{ zigbee2mqtt_network }}"
    state: "present"

- name: "Run zigbee2mqtt container"
  community.docker.docker_container:
    name: "{{ zigbee2mqtt_service_id }}"
    image: "koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}"
    networks:
      - name: "{{ zigbee2mqtt_network }}"
    state: "started"
    env: "{{ zigbee2mqtt_env }}"
    groups:
      - "dialout"
    devices:
      - "{{ zigbee2mqtt_device }}:/dev/ttyACM0"
    ports:
      - "{{ zigbee2mqtt_port }}:8080"
    volumes:
      - "{{ zigbee2mqtt_install_dir }}:/app/data"
    restart_policy: "unless-stopped"
