---
smarthome_docker_settings:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"

smarthome_env: {}

smarthome_user:
  name: "{{ ansible_user }}"
  password: "smarthome"

# /dev/ttyUSB0
smarthome_zigbee_adapter: ""
