---
# https://github.com/linuxserver/docker-homeassistant#parameters

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    homeassistant_service_id: "homeassistant"
    homeassistant_env: "{{ homeassistant_env_default | combine(homeassistant_env) }}"
    homeassistant_config: "{{ homeassistant_config_default | combine(homeassistant_config, recursive=true) }}"
    homeassistant_homekit_config: "{{ homeassistant_homekit_config_default | combine(homeassistant_homekit_config, recursive=true) }}"

- name: "Create service directories"
  ansible.builtin.file:
    path: "{{ homeassistant_install_dir }}"
    state: "directory"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0770"

- name: "Template configuration.yml"
  ansible.builtin.template:
    src: "configuration.yaml.j2"
    dest: "{{ homeassistant_install_dir }}/configuration.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: "Ensure {{ homeassistant_network }} network exists"
  when: homeassistant_network != "host"
  community.general.docker_network:
    name: "{{ homeassistant_network }}"
    state: "present"

- name: "Run homeassistant container"
  community.general.docker_container:
    name: "{{ homeassistant_service_id }}"
    image: "{{ homeassistant_avahi_image_name }}:{{ homeassistant_avahi_image_tag }}"
    networks:
      - name: "{{ homeassistant_network }}"
    state: "started"
    env: "{{ homeassistant_env }}"
    ports:
      - "{{ homeassistant_port }}:8123"
      - "{{ homeassistant_homekit_config.port }}:{{ homeassistant_homekit_config.port }}"
    volumes:
      - "{{ homeassistant_install_dir }}:/config"
    restart_policy: "unless-stopped"