---
# https://github.com/linuxserver/docker-homeassistant#parameters

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    homeassistant_service_id: "homeassistant"

- name: "Create service directories"
  ansible.builtin.file:
    path: "{{ homeassistant_install_dir }}"
    state: "directory"
    # owner: "{{ system_user_name }}"
    # group: "{{ system_user_group }}"
    mode: "0770"

- name: "Template configuration.yml"
  ansible.builtin.template:
    src: "configuration.yaml.j2"
    dest: "{{ homeassistant_install_dir }}/configuration.yaml"
    # owner: "{{ system_user_name }}"
    # group: "{{ system_user_group }}"
    mode: "0644"

- name: "Run homeassistant container"
  community.general.docker_container:
    name: "{{ homeassistant_service_id }}"
    image: "{{ homeassistant_avahi_image_name }}:{{ homeassistant_avahi_image_tag }}"
    networks:
      - name: "{{ homeassistant_docker_settings.network }}"
    state: "started"
    env:
      TZ: "{{ homeassistant_docker_settings.tz }}"
      PUID: "{{ homeassistant_docker_settings.puid }}"
      PGID: "{{ homeassistant_docker_settings.pgid }}"
    ports:
      - "{{ homeassistant_port }}:8123"
      - "{{ homeassistant_homekit_port }}:{{ homeassistant_homekit_port }}"
    volumes:
      - "{{ homeassistant_install_dir }}:/config"
    restart_policy: "unless-stopped"