---
# https://community.home-assistant.io/t/using-homekit-component-inside-docker/45409/45?page=2
# https://gnaneshkunal.github.io/avahi-docker-non-root.html
- name: "Build HomeAssistant image with Avahi"
  ansible.builtin.include_tasks: "avahi-image.yml"

- name: "Install and configure HomeAssistant"
  ansible.builtin.include_tasks: "homeassistant.yml"

- name: "Check if Avahi is installed"
  ansible.builtin.include_tasks: "check-avahi-installed.yml"

- name: "Install and configure mDNS repeater"
  when: homeassistant_avahi_installed
  ansible.builtin.include_tasks: "mdns.yml"
