---
# https://community.home-assistant.io/t/using-homekit-component-inside-docker/45409/45?page=2
- name: "Build HomeAssistant image with Avahi"
  ansible.builtin.include_tasks: "avahi-image.yml"

- name: "Install and configure HomeAssistant"
  ansible.builtin.include_tasks: "homeassistant.yml"

- name: "Install and configure mDNS repeater"
  ansible.builtin.include_tasks: "mdns.yml"