---
name: "Check code quality"

on:
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Lint"
        run: yamllint .
