---
name: "Release"

on:
  pull_request:
    branches:
      - "master"
  # push:
  #   tags:
  #     - '*'

jobs:

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Install Python 3"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"

      - name: "Install ansible-core"
        run: "pip3 install ansible-core"

      - name: "Publish to Ansible Galaxy"
        run: |
          ansible-galaxy collection publish --token ${{ secrets.GALAXY_API_KEY }} .