name: "Test (Ubuntu 22.04)"

on:
  pull_request:
    branches:
      - "master"

  push:
    branches:
      - "master"

  schedule:
    - cron: "0 7 * * 0"

jobs:
  test:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Print Ansible environment"
        run: "ansible --version"

      - name: "Install dependencies"
        run: |
          # fix ModuleNotFoundError: No module named 'requests'
          /opt/pipx/venvs/ansible-core/bin/python -m pip install requests

          ansible-galaxy install geerlingguy.docker
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install . -f

      - name: "Deploy containers with smarthome role"
        run: "ansible-playbook -i localhost .github/ansible/playbook-ci.yml -v -e \"ansible_user=${USER}\""

      - name: "Wait for containers to start"
        run: "sleep 60"

      - name: "Print docker logs"
        run: |
          docker ps -a
          docker logs homeassistant
          docker logs zigbee2mqtt
          docker logs mosquitto
